# main menu
[[main]]
name = "About Me"
url = "about/"
weight = 1

[[main]]
name = "Blog"
url = "#"
hasChildren = true
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 3


# footer menu
[[footer]]
name = "About"
url = "about"
weight = 2

[[footer]]
name = "Sitemap"
url = "sitemap.xml"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 7

[[footer]]
name = "Terms Conditions"
url = "terms-conditions"
weight = 8